### ISSUE TITLE
PHP Fatal error:  Uncaught ValueError: str_split(): Argument #2 ($length) must be greater than 0 

### ISSUE THREAD

**Issue by bluusun** [ppshobi/psonic#37]
Brew package installation. 

Sample code as per instructions.

Stack trace:
#0 /Users/...: str_split('hi Shobi how ar...', -55)
#1 /Users/..../src/Ingest.php(55): Psonic\Ingest->splitString('messagesCollect...', 'defaultBucket', '1234', 'hi Shobi how ar...')
#2 /Users/.../test.php(10): Psonic\Ingest->push('messagesCollect...', 'defaultBucket', '1234', 'hi Shobi how ar...')
#3 {main}
  thrown in /..../psonic/src/Ingest.php on line 146

**Comment by bluusun** [comment]
Seems like password was incorrect. A nicer error message would be appreciated :)

**Comment by ppshobi** [comment]
hmm. not sure how the -55 ended up there. do you have a way to reproduce this?

**Comment by johnmadrak** [comment]
@ppshobi 

I encountered this issue as well and wanted to share some insight.

With the following code:
```
$ingest = new Ingest(new Client('sonic', 1491, 10));
$ingest->connect('invalidpassword');
$ingest->flusho('examplecollection', 'default', 'a6d893ce-661e-4a6e-bf54-f3c046bb9638');
$ingest->push('examplecollection', 'default', 'a6d893ce-661e-4a6e-bf54-f3c046bb9638', 'test string');
```

`connect` does not trigger an exception.
`flusho` does not trigger an exception.
`push` triggers this exception.

I checked the return value of `connect` and `flusho` - the response contains a message from Sonic that says `ENDED authentication_failed`.

However, this message does not trigger any errors until `\Psonic\Ingest::splitString` is called because `bufferSize` is null.
