### ISSUE TITLE
Without $password for Psonic/Client

### ISSUE THREAD

**Issue by sergsoares** [ppshobi/psonic#5]
Inside [Api-Docs](https://github.com/ppshobi/psonic/blob/master/api-docs.md)

```
<?php

$search = new Psonic/Search(new Psonic/Client($host, $port, $password, $timeout));
echo $search->connect();
```

But in [Client.php](https://github.com/ppshobi/psonic/blob/ad9467677ea34028e36c515d50aa618f156872dc/src/Client.php#L26), this construct signature.

```
public function __construct($host = 'localhost', $port = 1491, $timeout = 30)
```

Some specific reason for help in this case ?

**Comment by ppshobi** [comment]
Well... That's a mistake, let me fix it ASAP. Actually the `$password` is not as part of the client instantiation, rather we supply the password with the StartChannel command, https://github.com/ppshobi/psonic/blob/ad9467677ea34028e36c515d50aa618f156872dc/src/Control.php#L31

But the tests were good because the default password is supplied as the default argument,

https://github.com/ppshobi/psonic/blob/ad9467677ea34028e36c515d50aa618f156872dc/src/Commands/Control/StartControlChannelCommand.php#L16

Thanks for pointing it out :)
